#!/bin/bash

WORKDIR="${HOME}/GPU_Malloc"
TF_VERSION="v1.11.0"
PYTHON_BIN="${HOME}/miniconda3/bin/python"

export PYTHON_BIN_PATH="${PYTHON_BIN}"
export PYTHON_LIB_PATH="${HOME}/miniconda3/lib/python3.6/site-packages"
export TF_NEED_JEMALLOC=1
export TF_NEED_GCP=0
export TF_NEED_HDFS=0
export TF_NEED_AWS=0
export TF_NEED_KAFKA=0
export TF_ENABLE_XLA=0
export TF_NEED_GDR=0
export TF_NEED_VERBS=0
export TF_NEED_NGRAPH=0
export TF_NEED_OPENCL_SYCL=0
export TF_NEED_CUDA=1
export TF_NEED_TENSORRT=0
export TF_NEED_MPI=0

export GCC_HOST_COMPILER_PATH="$(which gcc)"
export CUDA_TOOLKIT_PATH="/usr/local/cuda"
export TF_CUDA_VERSION="7.5"
export CUDNN_INSTALL_PATH="${WORKDIR}/cuda"
export TF_CUDNN_VERSION="6.0"
export TF_NCCL_VERSION="1.3"
export TF_CUDA_COMPUTE_CAPABILITIES="2.0" # SELFDISTRUCT
export TF_CUDA_CLANG=0
export CC_OPT_FLAGS="-mcpu=native"
export TF_SET_ANDROID_WORKSPACE=0

if [ ! -f ${HOME}/bin/bazel ]
then
	./prereq
fi

mkdir -p ${WORKDIR}
cd ${WORKDIR}

if [ ! -d "tensorflow" ]
then
	git clone https://github.com/tensorflow/tensorflow.git
fi

cd tensorflow
git checkout ${TF_VERSION}

./configure

bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg

${PYTHON_BIN} -m pip install /tmp/tensorflow_pkg/tensorflow-versio*
