#!/bin/bash

BAZEL_VERSION="0.17.2"

PYTHON_BIN="${HOME}/miniconda3/bin/python"

${PYTHON_BIN} -m pip install -U --user pip six numpy wheel mock
${PYTHON_BIN} -m pip install -U --user keras_applications==1.0.5 --no-deps
${PYTHON_BIN} -m pip install -U --user keras_preprocessing==1.0.3 --no-deps

if [ ! -f ~/bin/bazel ]
then
	wget https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh
	chmod +x bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh
	./bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh --user
	rm ./bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh
fi

